#!/bin/sh

# Test this implementation against
# https://reveng.sourceforge.io/crc-catalogue/

SCRIPT="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$0")"
cd "$SCRIPT_DIR"

set -eu

if ! command -v reveng >/dev/null; then
    cat <<'EOF' >&2
Please download and build the https://reveng.sourceforge.io/ software,
and put it on $PATH for this test. Ignoring this test for now.
EOF
    exit 0
fi

rm reveng.hpp || true

cat <<EOF >reveng.hpp
// Generated by $0 $@
#include "cpprc/crc.hpp"

using namespace std::literals;
using namespace Crc::Detail;
using enum Crc::Detail::Bitorder;

EOF

reveng -D | while read -r algo; do
    eval "$algo"
    if [ "$width" -ge 8 ] && [ "$width" -le 64 ]; then
        # C++ valid identifier
        id="$(echo $name | sed 's/[^0-9a-zA-Z_]/_/g')"

        # Convert to Bitorder
        inorder="Bitorder($refin)"
        outorder="Bitorder($refout)"
        cat <<EOF >>reveng.hpp
// $name
using $id = Impl<$width, ${poly}ull, ${init}ull, $inorder, $outorder, ${xorout}ull>;

static_assert($id{}.bitwise("123456789"sv) == ${check}ull, R"x($algo)x");
static_assert($id{}.tabled ("123456789"sv) == ${check}ull, R"x($algo)x");
EOF

        for i in `seq 10`; do
            # Generate some other test data
            data="$(cat /dev/urandom | tr -dc '0-9a-zA-Z' | head -c10)"
            hex="$(echo -n "$data" | xxd -p)"
            check="$(reveng -m "$name" -c $hex)"
            # reveng outputs it as bytes not integer so byteswap
            if [ "$refout" = true ]; then
                check="$(echo $check | tr -d '\n' | tac -r -s '[0-9a-f][0-9a-f]')"
            fi
            check="0x${check}ull"
            cat <<EOF >>reveng.hpp
static_assert($id{}.bitwise("${data}"sv) == ${check}, R"x($algo)x");
static_assert($id{}.tabled ("${data}"sv) == ${check}, R"x($algo)x");
EOF
        done
    fi
done
echo "Generating reveng.hpp done"

c++ -I../ -std=c++23 reveng.hpp -c
echo "RevEng test OK"
