#!/bin/sh

# Test this implementation against
# https://reveng.sourceforge.io/crc-catalogue/

SCRIPT="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$0")"
cd "$SCRIPT_DIR"

set -eu

if ! command -v reveng >/dev/null; then
    cat <<'EOF' >&2
Please download and build the https://reveng.sourceforge.io/ software,
and put it on $PATH for this test. Ignoring this test for now.
EOF
    exit 0
fi

rm reveng.hpp || true

cat <<EOF >reveng.hpp
// Generated by $0 $@
#include "cpprc/crc.hpp"

using namespace std::literals;
using namespace Crc::Detail;
using enum Crc::Detail::Bitorder;

EOF

reveng -D | while read -r algo; do
    eval "$algo"
    if [ "$width" -ge 8 ] && [ "$width" -le 64 ]; then
        # C++ valid identifier
        id="$(echo $name | sed 's/[^0-9a-zA-Z_]/_/g')"

        # Generate some other test data
        hello="Hello, world"
        # In hex/base16
        helloin="$(echo -n "${hello}" | xxd -p)"
        hellocheck="$(reveng -m "$name" -c $helloin)"
        # reveng outputs it as bytes not integer so byteswap
        if [ "$refout" = true ]; then
            hellocheck="$(echo $hellocheck | tr -d '\n' | tac -r -s '[0-9a-f][0-9a-f]')"
        fi
        hellocheck="0x${hellocheck}ull"

        # Convert to Bitorder
        refin="Bitorder($refin)"
        refout="Bitorder($refout)"
        cat <<EOF >>reveng.hpp
// $name
using $id = Impl<$width, ${poly}ull, ${init}ull, $refin, $refout, ${xorout}ull>;

static_assert($id{}.bitwise("123456789"sv) == ${check}ull, R"x($algo)x");
static_assert($id{}.tabled ("123456789"sv) == ${check}ull, R"x($algo)x");
static_assert($id{}.bitwise("${hello}"sv) == ${hellocheck}, R"x($algo)x");
static_assert($id{}.tabled ("${hello}"sv) == ${hellocheck}, R"x($algo)x");
EOF
    fi
done

c++ -I../ -std=c++23 reveng.hpp -c
echo "RevEng test OK"
