#!/bin/sh

cat <<EOF
// Generated by $0 $@
#include "cpprc/crc.hpp"

using namespace std::literals;
using namespace Crc::Detail;
using enum Crc::Detail::Bitorder;

EOF

./reveng-3.0.6/reveng -D | while read -r algo; do
    eval "$algo"
    if [ "$width" -ge 8 ] && [ "$width" -le 64 ]; then
        # C++ valid identifier
        id="$(echo $name | sed 's/[^0-9a-zA-Z_]/_/g')"

        # Generate some other test data
        hello="Hello, world"
        # In hex/base16
        helloin="$(echo -n "${hello}" | xxd -p)"
        hellocheck="$(./reveng-3.0.6/reveng -m "$name" -c $helloin)"
        # reveng outputs it as bytes not integer so byteswap
        if [ "$refout" = true ]; then
            hellocheck="$(echo $hellocheck | tr -d '\n' | tac -r -s '[0-9a-f][0-9a-f]')"
        fi
        hellocheck="0x${hellocheck}ull"

        # Convert to Bitorder
        refin="Bitorder($refin)"
        refout="Bitorder($refout)"
        cat <<EOF

// $name
using $id = Impl<$width, ${poly}ull, ${init}ull, $refin, $refout, ${xorout}ull>;

static_assert($id{}.bitwise("123456789"sv) == ${check}ull, R"x($algo)x");
static_assert($id{}.tabled ("123456789"sv) == ${check}ull, R"x($algo)x");
static_assert($id{}.bitwise("${hello}"sv) == ${hellocheck}, R"x($algo)x");
static_assert($id{}.tabled ("${hello}"sv) == ${hellocheck}, R"x($algo)x");
EOF
    fi
done
